"""test migrate

Revision ID: 40f00323600b
Revises: 
Create Date: 2021-07-06 14:34:10.081855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40f00323600b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('service')
    op.drop_table('auto')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('Surname', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Specialization', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('Rank', mysql.ENUM('1', '2', '3', '4', '5'), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('auto',
    sa.Column('VIN', mysql.VARCHAR(length=17), nullable=False),
    sa.Column('Number', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('Brand', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('Model', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Make', mysql.YEAR(display_width=4), nullable=True),
    sa.PrimaryKeyConstraint('VIN'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('service',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('Auto', mysql.VARCHAR(length=17), nullable=False),
    sa.Column('Owner', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Employee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Beginning', sa.DATE(), nullable=False),
    sa.Column('Completion', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['Auto'], ['auto.VIN'], name='service_ibfk_1'),
    sa.ForeignKeyConstraint(['Employee'], ['employees.ID'], name='service_ibfk_2'),
    sa.ForeignKeyConstraint(['Owner'], ['clients.ID'], name='service_ibfk_3'),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('clients',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('Surname', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
