"""empty message

Revision ID: b313ca52c3fa
Revises: 40f00323600b
Create Date: 2021-07-09 14:12:08.403011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b313ca52c3fa'
down_revision = '40f00323600b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('brand', sa.String(length=15), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('make', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('vin', 'brand', 'model', 'make'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto')
    # ### end Alembic commands ###
