"""clients table

Revision ID: e8e32f863e0c
Revises: b313ca52c3fa
Create Date: 2021-07-24 22:21:27.684744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8e32f863e0c'
down_revision = 'b313ca52c3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auto', sa.Column('owner', sa.Integer(), nullable=True))
    op.alter_column('auto', 'brand',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('auto', 'model',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('auto', 'make',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'auto', 'clients', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auto', type_='foreignkey')
    op.alter_column('auto', 'make',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('auto', 'model',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('auto', 'brand',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
    op.drop_column('auto', 'owner')
    op.drop_table('clients')
    # ### end Alembic commands ###
